# Generated by Django 5.2.4 on 2025-11-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('Placa de Vídeo', 'Placa de Vídeo'), ('Processador', 'Processador'), ('Placa Mãe', 'Placa Mãe'), ('Memória RAM', 'Memória RAM'), ('Armazenamento', 'Armazenamento'), ('Fonte', 'Fonte'), ('Gabinete', 'Gabinete')], max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque', models.IntegerField()),
            ],
        ),
    ]
