# Generated by Django 5.2.4 on 2025-11-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='estoque',
        ),
        migrations.AddField(
            model_name='item',
            name='watts',
            field=models.IntegerField(default=0, help_text='Consumo em Watts (TDP)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[('Processador', 'Processador'), ('Placa de Vídeo', 'Placa de Vídeo'), ('Placa Mãe', 'Placa Mãe'), ('Memória RAM', 'Memória RAM'), ('Armazenamento', 'Armazenamento'), ('Fonte', 'Fonte'), ('Gabinete', 'Gabinete'), ('Cooler', 'Cooler')], max_length=50),
        ),
    ]
