# Generated by Django 5.2.4 on 2025-11-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_item_estoque_item_watts_alter_item_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='link_loja',
            field=models.URLField(blank=True, help_text='Link para compra', max_length=500, null=True),
        ),
    ]
