# Generated by Django 5.2.4 on 2025-11-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_item_link_loja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='link_loja',
        ),
        migrations.AddField(
            model_name='item',
            name='comprado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='links_json',
            field=models.TextField(default='[]'),
        ),
    ]
